services:
  - type: web
    name: tshirt-brand-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mahdeereshid_db_user:mahrita123%40@mhadee.yiywnor.mongodb.net/tshirt_brand
      - key: JWT_SECRET
        value: your_super_secret_key_change_in_production_2024
      - key: NODE_ENV
        value: production
